### broker services
GET http://localhost:9998/ops/services

### broker connections
GET http://localhost:9998/ops/connections

### brokers
GET http://localhost:9998/ops/brokers

### stop broker
POST http://localhost:9998/ops/stop_local_broker

### update config
POST http://localhost:9998/config/refresh/rsocket-config-client
Authorization: Bearer your_jwt_token_here
Content-Type: text/plain

developer=leijuan

### Get last config
GET http://localhost:9998/config/last/rsocket-config-client
Authorization: Bearer your_jwt_token_here

### metrics with prometheus
GET http://localhost:9997/actuator/prometheus

### broadcast demo
POST http://127.0.0.1:9998/ops/broadcast/demo
Content-Type: application/json

{
  "id": 1,
  "nick": "leijuan"
}

### app query
GET http://localhost:9998/app/rsocket-user-service

### prometheus app targets for file_sd_configs
GET http://localhost:9998/metrics/prometheus/app/targets

### prometheus broker targets for file_sd_configs
GET http://localhost:9998/metrics/prometheus/broker/targets

### metrics scrape
GET http://localhost:9998/metrics/b739c100-9c4c-4eac-96fd-00821716fedb

