# setup ToxiProxy
setup:
   brew tap shopify/shopify
   brew install toxiproxy

# start ToxiProxy
start_proxy:
   toxiproxy-server -config toxiproxy.json &

# create proxy channel for broker
create_broker_proxy_1:
   toxiproxy-cli create broker_proxy_1 --listen 0.0.0.0:19999 --upstream localhost:9999

k8s-deploy:
   kubectl apply -f src/main/k8s/deployment.yml

k8s-undeploy:
   kubectl delete -f src/main/k8s/deployment.yml

# setup kubernetes: create rsocket namespace and acl
k8s-setup:
   kubectl apply -f src/main/k8s/setup.yml