### REST API Gateway
POST http://127.0.0.1:9998/api/com.alibaba.user.UserService/findById
Authorization: Bearer jwt_token
Content-Type: application/json

[
  1
]

### user save
POST http://127.0.0.1:8282/com.alibaba.user.UserService/save
Authorization: Bearer jwt_token
Content-Type: application/json

[
  {
    "nick": "xxx",
    "email:": "xxx@yyy.com",
    "phone": "186111111"
  }
]

###
