### get user info
GET http://localhost:8181/user/2

### get user info from Spring RSocketRequester
GET http://localhost:8181/user/requester/2

### get user info from default method
GET http://localhost:8181/user/default/2

### get user info from extra
GET http://localhost:8181/user/extra/2

### get user info by bytebuf
GET http://localhost:8181/bytebuf/user/2

### Get Avatar with ByteBuf return
GET http://localhost:8181/user/avatar

### ByteBuf as param and ByteBuf as return
GET http://localhost:8181/user/bytebuf

### get account info
GET http://localhost:8181/account/1

### get user info with rx api
GET http://localhost:8181/rx/user/2

### get user info with rx api
GET http://localhost:8181/rx3/user/2

### get all user
GET http://localhost:8181/users

### get error
GET http://localhost:8181/error

### FNF
GET http://localhost:8181/job1

### Channel1 with Flux
GET http://localhost:8181/channel1

### Channel2 with param & Flux
GET http://localhost:8181/channel2

### channel with Mono return
GET http://localhost:8181/monoChannel

### save user
POST http://localhost:8181/user/save
Content-Type: application/json

{
  "id": "1",
  "nick": "Jackie"
}

### get app name
GET http://localhost:8181/appName

### enable flux
GET http://localhost:8181/flux

### metrics with prometheus format
GET http://localhost:8181/actuator/prometheus

###
