### Invoke uppercase function
POST http://localhost:8182/com.alibaba.WordService.uppercase
Content-Type: application/json

"hello"

### Invoke lowercase function
POST http://localhost:8182/com.alibaba.WordService.lowercase
Content-Type: application/json

"HELLO"