findById:
   grpcurl -plaintext -d "1" localhost:50051 com.alibaba.account.AccountService/findById

findByStatus:
   grpcurl -plaintext -d "1" localhost:50051 com.alibaba.account.AccountService/findByStatus

findByIdStream:
   grpcurl -plaintext -d @ localhost:50051 com.alibaba.account.AccountService/findByIdStream

services:
   grpcurl -plaintext localhost:50051 list