server:
  port: 8081

#rsocket
rsocket:
  brokers: tcp://127.0.0.1:9999
  port: 48081
  jwt-token: xxx

### management
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always


spring:
  application:
    name: demo-responder

#logging
logging:
  level.root: info
